### ISSUE TITLE
QScroller issuing console.log statements

### ISSUE THREAD

**Issue by digiproductmarketer** [quasarframework/app-extension-qscroller#5]
QScroller seems to be issuing console.log statements when scrolling the scroller.

I was using the console in the inspector for something else when I suddenly started getting log statements when scroll my QScroller

Mainly stating "update position" .. but also "no selected item found ..."

**Comment by hawkeye64** [comment]
hmmm, thanks for this. I'll look into it.

**Comment by hawkeye64** [comment]
Will be fixed in next release.
